### ISSUE TITLE
The Docker image on Docker Hub is still on Tinkerpop 3.3.0

### ISSUE THREAD

**Issue by kristallizer** [bricaud/gremlin-server#5]
Is it possible to push the latest version to Docker Hub?

**Comment by kristallizer** [comment]
@bricaud, pinging you just in case you missed it.

**Comment by bricaud** [comment]
Sure, I will do it when I am back from holidays. Or you can make a pull request.

**Comment by kristallizer** [comment]
I think only the image owner can push to Docker Hub. https://hub.docker.com/r/bricaud/gremlin-server/ does say that it is an "automated build" but it looks like it gave up 7 months ago after a failed build.

**Comment by bricaud** [comment]
OK, sorry, I did not understand.
I have done it. It should be available under the tag 3.3.3

**Comment by kristallizer** [comment]
Great, thanks!
